---
- name: Configuración automatica de servidor web
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Instalar paquete apache2
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Asegurar que el servicio Apache este activo
      service:
        name: apache2
        state: started
        enabled: yes
