---
- name: Securizacion automatica del servidor
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Instalar Firewall (UFW) y Fail2Ban
      apt:
        name: ["ufw", "fail2ban"]
        state: present

    - name: Permitir trafico Web (puerto 80)
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Permitir trafico SSH (puerto 22)
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Activar el Firewall y establecer politica por defecto
      ufw:
        state: enabled
        policy: deny
